import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { COMPONENT_PREFIX } from "../../../scripts/constants";
import { exportMap } from "./export-map";

const INDEX_FILE = resolve(import.meta.dirname, "../src/index.ts");
function generateIndexFile(): void {
  const imports = Object.entries(exportMap)
    .map(([name, component]) => `import ${name} from "${component}";`)
    .join("\n");

  const generatedContent = `
  // This file is generated by scripts/generate-exports.ts
  import type { App } from "vue";
  ${imports}

  export { ${Object.keys(exportMap).join(", ")} };
  export default {
     install(app: App) {
      ${Object.entries(exportMap)
        .map(([name]) => `app.component("${name}", ${name});`)
        .join("\n")}
     },
  }
`;

  console.log(generatedContent);

  writeFileSync(INDEX_FILE, generatedContent, "utf-8");
  console.log("✅ 已自动生成组件导出语句");
  console.log(`📦 组件列表: ${Object.keys(exportMap).join(", ")}`);
  console.log(`🏷️  前缀: ${COMPONENT_PREFIX}`);
  console.log(
    `📝 导出名: ${Object.keys(exportMap)
      .map((n) => `${COMPONENT_PREFIX}${n}`)
      .join(", ")}`
  );
}

// 执行生成
generateIndexFile();
